version: "3.9"

services:
    mssql:
      image: mcr.microsoft.com/azure-sql-edge:latest
      volumes:
        - events_mssql:/var/opt/mssql
      ports:
        - 1433:1433
      
      environment:
        - ACCEPT_EULA=1
        - MSSQL_SA_PASSWORD=retailstore@123

volumes:
    events_mssql: